import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {
        extend: {
            colors: {
                'error-container': '#ffdad6',
                'on-secondary-container': '#5c647a',
                'inverse-on-surface': '#f1effa',
                'on-primary': '#ffffff',
                'on-error-container': '#93000a',
                'on-primary-container': '#fffbff',
                'primary-fixed': '#e1e0ff',
                'on-tertiary': '#ffffff',
                'surface-container-low': '#f4f2fd',
                'on-surface-variant': '#464554',
                'surface-container-lowest': '#ffffff',
                'surface-bright': '#fbf8ff',
                'secondary-fixed-dim': '#bec6e0',
                'tertiary-fixed-dim': '#ffb783',
                'tertiary': '#904900',
                'on-primary-fixed-variant': '#2f2ebe',
                'on-tertiary-fixed': '#301400',
                'surface': '#fbf8ff',
                'inverse-surface': '#2f3038',
                'surface-tint': '#494bd6',
                'secondary-container': '#dae2fd',
                'primary-container': '#6063ee',
                'tertiary-fixed': '#ffdcc5',
                'error': '#ba1a1a',
                'surface-variant': '#e3e1ec',
                'surface-container-high': '#e8e7f1',
                'background': '#fbf8ff',
                'on-tertiary-container': '#fffbff',
                'on-tertiary-fixed-variant': '#703700',
                'secondary': '#565e74',
                'surface-container': '#eeedf7',
                'on-surface': '#1a1b22',
                'outline': '#767586',
                'on-primary-fixed': '#07006c',
                'on-background': '#1a1b22',
                'on-secondary-fixed-variant': '#3f465c',
                'primary': '#4648d4',
                'on-secondary': '#ffffff',
                'primary-fixed-dim': '#c0c1ff',
                'secondary-fixed': '#dae2fd',
                'inverse-primary': '#c0c1ff',
                'surface-dim': '#dad9e3',
                'on-error': '#ffffff',
                'outline-variant': '#c7c4d7',
                'surface-container-highest': '#e3e1ec',
                'on-secondary-fixed': '#131b2e',
                'tertiary-container': '#b55d00',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                sm: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                '2xl': '0.75rem',
                full: '0.75rem',
            },
            spacing: {
                'gutter': '16px',
                'stack-sm': '8px',
                'stack-md': '16px',
                'stack-lg': '32px',
                'sidebar': '260px',
            },
            fontFamily: {
                sans: ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
            },
        },
    },

    plugins: [forms],
};
